imports

In [3]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, precision_score, recall_score
from sklearn.model_selection import StratifiedKFold, cross_validate

In [4]:

def preprocess(file_path,split_value,target_column_index,has_header):
    """this function is used for taking the dataset from .csv file making a test train split
    and x, y split (has header is either True or False)"""

    #reading the .csv
    if has_header:
        df = pd.read_csv(file_path, header=0, delimiter=",")  # First row as header
        print(f"Dataset shape: {df.shape}")
        print(f"Column names: {list(df.columns)}")
    else:
        df = pd.read_csv(file_path, header=None, delimiter=",")  # No header row
        print(f"Dataset shape: {df.shape}")

    #making target variable split
    x_ds = df.drop(df.columns[target_column_index], axis=1)  # All except target
    y_ds = df.iloc[:, target_column_index]  # Target column only

    #making test train split
    x_train, x_test, y_train, y_test = train_test_split(x_ds, y_ds, test_size=split_value, random_state=10, shuffle= True)
    print(f'shape of x training: {x_train.shape}')
    print(f'shape of x testing: {x_test.shape}')

    return x_train, x_test, y_train, y_test, x_ds, y_ds

making target variable numarical(optional)

In [5]:
def implement(model):
    """this function contains implementation (modeling and fitting) on the dataset with 1 
    initiations and shows the results of the implementations. (it needs to take target variable varieties ).
    Note: This function doesn't have compile it is not appoprate to use this function for perceptron learning algs.
    because it doesn't have training vs test accuracy comparison and doesn't have epochs and .argmax(axis=1) """
    #initiante ml
    model.fit(x_train, y_train)
    #model evaluation
    y_pred = model.predict(x_test)

    print(f'Classification report: {classification_report(y_test, y_pred)}')
    print(f"Accuracy score is: {accuracy_score(y_test,y_pred)}")
    print(f"Percision score is: {precision_score(y_test,y_pred, average='weighted')}")
    print(f"Recall score is: {recall_score(y_test,y_pred, average='weighted')}")
    print(f'Confusion matrix: {confusion_matrix(y_test, y_pred)}')

    # StratifiedKFold evaluations
    skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=10)
    scoring = ['accuracy', 'precision_weighted', 'recall_weighted']
    cv_results = cross_validate(model, x_ds, y_ds, cv=skf, scoring=scoring)
    print(f"StratifiedKFold CV Accuracy: {cv_results['test_accuracy'].mean():.4f} (+/- {cv_results['test_accuracy'].std() * 2:.4f})")
    print(f"StratifiedKFold CV Precision: {cv_results['test_precision_weighted'].mean():.4f} (+/- {cv_results['test_precision_weighted'].std() * 2:.4f})")
    print(f"StratifiedKFold CV Recall: {cv_results['test_recall_weighted'].mean():.4f} (+/- {cv_results['test_recall_weighted'].std() * 2:.4f})")
        

Run the preprocess for diffrent datasets

In [6]:
x_train, x_test, y_train, y_test, x_ds, y_ds = preprocess("beans_kmeans.csv", 0.2, 16, True)

Dataset shape: (13611, 17)
Column names: ['Area', 'Perimeter', 'MajorAxisLength', 'MinorAxisLength', 'AspectRation', 'Eccentricity', 'ConvexArea', 'EquivDiameter', 'Extent', 'Solidity', 'roundness', 'Compactness', 'ShapeFactor1', 'ShapeFactor2', 'ShapeFactor3', 'ShapeFactor4', 'Class']
shape of x training: (10888, 16)
shape of x testing: (2723, 16)


In [11]:
x_train, x_test, y_train, y_test, x_ds, y_ds = preprocess("diabetes_kmeans.csv", 0.2, 8, True)

Dataset shape: (768, 9)
Column names: ['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age', 'Outcome']
shape of x training: (614, 8)
shape of x testing: (154, 8)


In [ ]:
x_train, x_test, y_train, y_test, x_ds, y_ds = preprocess("divorce.csv", 0.2, 54, True)

In [ ]:
x_train, x_test, y_train, y_test, x_ds, y_ds = preprocess("parkinsons_kmeans.csv", 0.2, 17, True)

In [ ]:
x_train, x_test, y_train, y_test, x_ds, y_ds = preprocess("rice_binned_kmeans.csv", 0.2, 7, True)

In [ ]:
x_train, x_test, y_train, y_test, x_ds, y_ds = preprocess("wdbc_binned_kmeans.csv", 0.2, 1, True)

Run the implement function for diffrent models

In [7]:
#KNN
from sklearn.neighbors import KNeighborsClassifier
implement(KNeighborsClassifier())

Classification report:               precision    recall  f1-score   support

    BARBUNYA       0.93      0.91      0.92       233
      BOMBAY       1.00      0.99      1.00       118
        CALI       0.93      0.94      0.93       330
    DERMASON       0.90      0.91      0.90       706
       HOROZ       0.97      0.93      0.95       396
       SEKER       0.95      0.94      0.94       411
        SIRA       0.84      0.85      0.85       529

    accuracy                           0.91      2723
   macro avg       0.93      0.93      0.93      2723
weighted avg       0.92      0.91      0.91      2723

Accuracy score is: 0.9144326110907087
Percision score is: 0.9151220519996149
Recall score is: 0.9144326110907087
Confusion matrix: [[213   0  14   0   1   1   4]
 [  0 117   1   0   0   0   0]
 [ 11   0 310   0   6   1   2]
 [  0   0   0 643   0   9  54]
 [  0   0   7   5 370   0  14]
 [  4   0   0  11   0 385  11]
 [  1   0   3  59   5   9 452]]
StratifiedKFold CV Accuracy: 0.

In [8]:
#Ada Boost
from sklearn.ensemble import AdaBoostClassifier 
implement(AdaBoostClassifier(n_estimators=100, random_state = 10))

Classification report:               precision    recall  f1-score   support

    BARBUNYA       0.91      0.74      0.82       233
      BOMBAY       1.00      1.00      1.00       118
        CALI       0.82      0.75      0.78       330
    DERMASON       0.89      0.79      0.84       706
       HOROZ       0.78      0.96      0.86       396
       SEKER       0.87      0.89      0.88       411
        SIRA       0.76      0.83      0.79       529

    accuracy                           0.84      2723
   macro avg       0.86      0.85      0.85      2723
weighted avg       0.84      0.84      0.84      2723

Accuracy score is: 0.8380462724935732
Percision score is: 0.8439346547498877
Recall score is: 0.8380462724935732
Confusion matrix: [[173   0  50   0   5   1   4]
 [  0 118   0   0   0   0   0]
 [  6   0 247   0  75   1   1]
 [  0   0   0 559  10  25 112]
 [  1   0   3   2 380   0  10]
 [  8   0   0  25   0 367  11]
 [  3   0   2  39  20  27 438]]


e:\VS Code Projects\ppfs_mlpart\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
e:\VS Code Projects\ppfs_mlpart\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
e:\VS Code Projects\ppfs_mlpart\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result

StratifiedKFold CV Accuracy: 0.8327 (+/- 0.0625)
StratifiedKFold CV Precision: 0.8318 (+/- 0.0727)
StratifiedKFold CV Recall: 0.8327 (+/- 0.0625)


e:\VS Code Projects\ppfs_mlpart\.venv\Lib\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])


In [9]:
#SVM
from sklearn.svm import SVC 
implement(SVC(max_iter = -1, random_state=10))

Classification report:               precision    recall  f1-score   support

    BARBUNYA       0.93      0.93      0.93       233
      BOMBAY       1.00      1.00      1.00       118
        CALI       0.94      0.95      0.95       330
    DERMASON       0.92      0.91      0.91       706
       HOROZ       0.96      0.93      0.94       396
       SEKER       0.95      0.93      0.94       411
        SIRA       0.85      0.89      0.87       529

    accuracy                           0.92      2723
   macro avg       0.94      0.93      0.94      2723
weighted avg       0.92      0.92      0.92      2723

Accuracy score is: 0.922879177377892
Percision score is: 0.923644267397618
Recall score is: 0.922879177377892
Confusion matrix: [[216   0  11   0   1   1   4]
 [  0 118   0   0   0   0   0]
 [ 10   0 313   0   5   1   1]
 [  0   0   0 644   1   9  52]
 [  0   0   8   7 369   0  12]
 [  6   0   0  10   0 383  12]
 [  0   0   0  41  10   8 470]]
StratifiedKFold CV Accuracy: 0.923

In [10]:
#Gaussian Naive Bayes
from sklearn.naive_bayes import GaussianNB 
implement(GaussianNB())

Classification report:               precision    recall  f1-score   support

    BARBUNYA       0.82      0.77      0.79       233
      BOMBAY       1.00      0.99      1.00       118
        CALI       0.85      0.90      0.87       330
    DERMASON       0.94      0.86      0.90       706
       HOROZ       0.96      0.92      0.94       396
       SEKER       0.91      0.94      0.93       411
        SIRA       0.79      0.89      0.84       529

    accuracy                           0.89      2723
   macro avg       0.90      0.90      0.90      2723
weighted avg       0.89      0.89      0.89      2723

Accuracy score is: 0.8887256702166728
Percision score is: 0.8924397974910343
Recall score is: 0.8887256702166728
Confusion matrix: [[179   0  42   0   0   1  11]
 [  1 117   0   0   0   0   0]
 [ 27   0 297   0   4   1   1]
 [  0   0   0 604   0  20  82]
 [  0   0  11   6 365   0  14]
 [  5   0   0   5   0 387  14]
 [  6   0   0  27  11  14 471]]
StratifiedKFold CV Accuracy: 0.

In [11]:
#Random Forests
from sklearn.ensemble import RandomForestClassifier
implement(RandomForestClassifier())


Classification report:               precision    recall  f1-score   support

    BARBUNYA       0.91      0.92      0.91       233
      BOMBAY       1.00      1.00      1.00       118
        CALI       0.94      0.93      0.94       330
    DERMASON       0.89      0.92      0.90       706
       HOROZ       0.96      0.92      0.94       396
       SEKER       0.95      0.93      0.94       411
        SIRA       0.85      0.86      0.86       529

    accuracy                           0.91      2723
   macro avg       0.93      0.93      0.93      2723
weighted avg       0.92      0.91      0.91      2723

Accuracy score is: 0.9144326110907087
Percision score is: 0.9153492253695523
Recall score is: 0.9144326110907087
Confusion matrix: [[214   0   9   0   1   2   7]
 [  0 118   0   0   0   0   0]
 [ 14   0 308   0   6   1   1]
 [  0   0   0 648   1   8  49]
 [  2   0   8  10 363   0  13]
 [  3   0   0  16   0 382  10]
 [  2   0   1  55   7   7 457]]
StratifiedKFold CV Accuracy: 0.

In [12]:
#Decesion Trees
from sklearn.tree import DecisionTreeClassifier
implement(DecisionTreeClassifier())

Classification report:               precision    recall  f1-score   support

    BARBUNYA       0.85      0.88      0.86       233
      BOMBAY       1.00      1.00      1.00       118
        CALI       0.91      0.92      0.91       330
    DERMASON       0.86      0.88      0.87       706
       HOROZ       0.95      0.91      0.93       396
       SEKER       0.93      0.90      0.91       411
        SIRA       0.80      0.80      0.80       529

    accuracy                           0.88      2723
   macro avg       0.90      0.90      0.90      2723
weighted avg       0.88      0.88      0.88      2723

Accuracy score is: 0.8817480719794345
Percision score is: 0.8826866527416461
Recall score is: 0.8817480719794345
Confusion matrix: [[205   0  17   0   2   1   8]
 [  0 118   0   0   0   0   0]
 [ 14   0 303   0  10   2   1]
 [  0   0   0 624   4  12  66]
 [  5   0   9   6 359   0  17]
 [  6   0   0  19   0 369  17]
 [ 11   0   4  74   3  14 423]]
StratifiedKFold CV Accuracy: 0.