imports

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, precision_score, recall_score
from sklearn.model_selection import StratifiedKFold, cross_validate

In [ ]:

def preprocess(file_path,split_value,target_column_index,has_header,delete_index_list):
    """this function is used for taking the dataset from .csv file making a test train split
    and x, y split (has header is either True or False)"""

    #reading the .csv
    if has_header:
        df = pd.read_csv(file_path, header=0, delimiter=",")  # First row as header
        print(f"Dataset shape: {df.shape}")
        print(f"Column names: {list(df.columns)}")
    else:
        df = pd.read_csv(file_path, header=None, delimiter=",")  # No header row
        print(f"Dataset shape: {df.shape}")

    df.drop(df.columns[delete_index_list], axis=1)
    
    #making target variable split
    x_ds = df.drop(df.columns[target_column_index], axis=1)  # All except target
    y_ds = df.iloc[:, target_column_index]  # Target column only

    #making test train split
    x_train, x_test, y_train, y_test = train_test_split(x_ds, y_ds, test_size=split_value, random_state=10, shuffle= True)
    print(f'shape of x training: {x_train.shape}')
    print(f'shape of x testing: {x_test.shape}')

    return x_train, x_test, y_train, y_test, x_ds, y_ds

In [3]:
def implement(model):
    """this function contains implementation (modeling and fitting) on the dataset with 1 
    initiation and shows the results of the implementations.
    Note: This function doesn't have compile so it is not appoprate to use this function for perceptron learning algs.
    because it doesn't have training vs test accuracy comparison and doesn't have epochs and .argmax(axis=1) """
    #initiante ml
    model.fit(x_train, y_train)
    #model evaluation
    y_pred = model.predict(x_test)

    print(f'Classification report: {classification_report(y_test, y_pred)}')
    print(f"Accuracy score is: {accuracy_score(y_test,y_pred)}")
    print(f"Percision score is: {precision_score(y_test,y_pred, average='weighted')}")
    print(f"Recall score is: {recall_score(y_test,y_pred, average='weighted')}")
    print(f'Confusion matrix: \n{confusion_matrix(y_test, y_pred)}')

    # StratifiedKFold evaluations
    skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=10)
    scoring = ['accuracy', 'precision_weighted', 'recall_weighted']
    cv_results = cross_validate(model, x_ds, y_ds, cv=skf, scoring=scoring)
    print(f"StratifiedKFold CV Accuracy: {cv_results['test_accuracy'].mean():.4f} (+/- {cv_results['test_accuracy'].std() * 2:.4f})")
    print(f"StratifiedKFold CV Precision: {cv_results['test_precision_weighted'].mean():.4f} (+/- {cv_results['test_precision_weighted'].std() * 2:.4f})")
    print(f"StratifiedKFold CV Recall: {cv_results['test_recall_weighted'].mean():.4f} (+/- {cv_results['test_recall_weighted'].std() * 2:.4f})")
        

Select the dataset!

Runs the preprocess for diffrent datasets.

In [ ]:
x_train, x_test, y_train, y_test, x_ds, y_ds = preprocess("beans_kmeans.csv", 0.2, 16, True, [])

Dataset shape: (13611, 17)
Column names: ['Area', 'Perimeter', 'MajorAxisLength', 'MinorAxisLength', 'AspectRation', 'Eccentricity', 'ConvexArea', 'EquivDiameter', 'Extent', 'Solidity', 'roundness', 'Compactness', 'ShapeFactor1', 'ShapeFactor2', 'ShapeFactor3', 'ShapeFactor4', 'Class']
shape of x training: (10888, 16)
shape of x testing: (2723, 16)


x_train, x_test, y_train, y_test, x_ds, y_ds = preprocess("diabetes_kmeans.csv", 0.2, 8, True)

x_train, x_test, y_train, y_test, x_ds, y_ds = preprocess("divorce.csv", 0.2, 54, True)

x_train, x_test, y_train, y_test, x_ds, y_ds = preprocess("parkinsons_kmeans.csv", 0.2, 17, True)

x_train, x_test, y_train, y_test, x_ds, y_ds = preprocess("rice_binned_kmeans.csv", 0.2, 7, True)

x_train, x_test, y_train, y_test, x_ds, y_ds = preprocess("wdbc_binned_kmeans.csv", 0.2, 1, True)

Run the implement function for diffrent models

In [5]:
#KNN
from sklearn.neighbors import KNeighborsClassifier
implement(KNeighborsClassifier())

Classification report:               precision    recall  f1-score   support

    BARBUNYA       0.93      0.91      0.92       233
      BOMBAY       1.00      0.99      1.00       118
        CALI       0.93      0.94      0.93       330
    DERMASON       0.89      0.91      0.90       706
       HOROZ       0.97      0.93      0.95       396
       SEKER       0.96      0.93      0.94       411
        SIRA       0.84      0.85      0.85       529

    accuracy                           0.91      2723
   macro avg       0.93      0.93      0.93      2723
weighted avg       0.92      0.91      0.91      2723

Accuracy score is: 0.9144326110907087
Percision score is: 0.9151932860775547
Recall score is: 0.9144326110907087
Confusion matrix: 
[[213   0  14   0   1   1   4]
 [  0 117   1   0   0   0   0]
 [ 11   0 310   0   6   1   2]
 [  0   0   0 645   0   8  53]
 [  0   0   7   5 370   0  14]
 [  4   0   0  12   0 384  11]
 [  1   0   2  62   5   8 451]]
StratifiedKFold CV Accuracy: 0

In [6]:
#Ada Boost
from sklearn.ensemble import AdaBoostClassifier 
implement(AdaBoostClassifier(n_estimators=100, random_state = 10))

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/L

Classification report:               precision    recall  f1-score   support

    BARBUNYA       0.00      0.00      0.00       233
      BOMBAY       1.00      1.00      1.00       118
        CALI       0.00      0.00      0.00       330
    DERMASON       0.00      0.00      0.00       706
       HOROZ       0.30      0.90      0.45       396
       SEKER       0.76      0.18      0.29       411
        SIRA       0.18      0.44      0.26       529

    accuracy                           0.29      2723
   macro avg       0.32      0.36      0.28      2723
weighted avg       0.24      0.29      0.20      2723

Accuracy score is: 0.2879177377892031
Percision score is: 0.2354834564375573
Recall score is: 0.2879177377892031
Confusion matrix: 
[[  0   0   0   0 230   1   2]
 [  0 118   0   0   0   0   0]
 [  0   0   0   0 329   1   0]
 [  0   0   0   0   0   0 706]
 [  0   0   0   0 357   0  39]
 [  0   0   0   0  14  74 323]
 [  0   0   0   0 272  22 235]]


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/ensemble/_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/L

StratifiedKFold CV Accuracy: 0.3419 (+/- 0.2337)
StratifiedKFold CV Precision: 0.2959 (+/- 0.2219)
StratifiedKFold CV Recall: 0.3419 (+/- 0.2337)


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
#SVM
from sklearn.svm import SVC 
implement(SVC(max_iter = -1, random_state=10))

In [ ]:
#Gaussian Naive Bayes
from sklearn.naive_bayes import GaussianNB 
implement(GaussianNB())

In [ ]:
#Random Forests
from sklearn.ensemble import RandomForestClassifier
implement(RandomForestClassifier())


In [ ]:
#Decesion Trees
from sklearn.tree import DecisionTreeClassifier
implement(DecisionTreeClassifier())