imports

In [93]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, precision_score, recall_score
from sklearn.model_selection import StratifiedKFold, cross_validate

In [94]:

def preprocess(file_path,split_value,target_column_index,has_header,delete_list,extraction_list):
    """this function is used for taking the dataset from .csv file making a test train split
    and x, y split (has header is either True or False)"""

    #reading the .csv
    if has_header:
        df = pd.read_csv(file_path, header=0, delimiter=",")  # First row as header
        print(f"Dataset shape: {df.shape}")
        print(f"Column names: {list(df.columns)}")
    else:
        df = pd.read_csv(file_path, header=None, delimiter=",")  # No header row
        print(f"Dataset shape: {df.shape}")

    
    #making target variable split
    x_ds = df.drop(df.columns[target_column_index], axis=1)  # All except target
    y_ds = df.iloc[:, target_column_index]  # Target column only

    x_ds = x_ds.drop(columns = delete_list + extraction_list)
    #making test train split
    x_train, x_test, y_train, y_test = train_test_split(x_ds, y_ds, test_size=split_value, random_state=10, shuffle= True)
    print(f'shape of x training: {x_train.shape}')
    print(f'shape of x testing: {x_test.shape}')

    return x_train, x_test, y_train, y_test, x_ds, y_ds

In [95]:
def implement(model):
    """this function contains implementation (modeling and fitting) on the dataset with 1 
    initiation and shows the results of the implementations.
    Note: This function doesn't have compile so it is not appoprate to use this function for perceptron learning algs.
    because it doesn't have training vs test accuracy comparison and doesn't have epochs and .argmax(axis=1) """
    #initiante ml
    model.fit(x_train, y_train)
    #model evaluation
    y_pred = model.predict(x_test)

    print(f'Confusion matrix: \n{confusion_matrix(y_test, y_pred)}')
    print(f'Classification report: {classification_report(y_test, y_pred)}')
    print(f"Accuracy score is: {accuracy_score(y_test,y_pred)}")
    print(f"Precision score is: {precision_score(y_test,y_pred, average='weighted')}")
    print(f"Recall score is: {recall_score(y_test,y_pred, average='weighted')}")
    
    # StratifiedKFold evaluations
    skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=10)
    scoring = ['accuracy', 'precision_weighted', 'recall_weighted']
    cv_results = cross_validate(model, x_ds, y_ds, cv=skf, scoring=scoring)
    print(f"StratifiedKFold CV Accuracy: {cv_results['test_accuracy'].mean():.4f} (+/- {cv_results['test_accuracy'].std() * 2:.4f})")
    print(f"StratifiedKFold CV Precision: {cv_results['test_precision_weighted'].mean():.4f} (+/- {cv_results['test_precision_weighted'].std() * 2:.4f})")
    print(f"StratifiedKFold CV Recall: {cv_results['test_recall_weighted'].mean():.4f} (+/- {cv_results['test_recall_weighted'].std() * 2:.4f})")
        

Select the dataset!

Runs the preprocess for diffrent datasets.

x_train, x_test, y_train, y_test, x_ds, y_ds = preprocess("beans_kmeans.csv", 0.2, 16, True, [], [])

x_train, x_test, y_train, y_test, x_ds, y_ds = preprocess("beans_kmeans.csv", 0.2, 16, True, [],["ShapeFactor2","Compactness","ShapeFactor3","roundness","MajorAxisLength","Eccentricity","AspectRation"] )

x_train, x_test, y_train, y_test, x_ds, y_ds = preprocess("diabetes_kmeans.csv", 0.2, 8, True, [], [])

x_train, x_test, y_train, y_test, x_ds, y_ds = preprocess("diabetes_kmeans.csv", 0.2, 8, True, [], [])

x_train, x_test, y_train, y_test, x_ds, y_ds = preprocess("divorce.csv", 0.2, 54, True, [], [])

x_train, x_test, y_train, y_test, x_ds, y_ds = preprocess("divorce.csv", 0.2, 54, True, [], ['Atr32','Atr33','Atr34','Atr35','Atr36','Atr52','Atr54'])

x_train, x_test, y_train, y_test, x_ds, y_ds = preprocess("parkinsons_kmeans.csv", 0.2, 17, True, ['name'], [])

x_train, x_test, y_train, y_test, x_ds, y_ds = preprocess("parkinsons_kmeans.csv", 0.2, 17, True, ['name'], ['spread1','HNR','PPE','MDVP:APQ'])

x_train, x_test, y_train, y_test, x_ds, y_ds = preprocess("rice_binned_kmeans.csv", 0.2, 7, True, [], ['Eccentricity', 'Major_Axis_Length', 'Perimeter'])

x_train, x_test, y_train, y_test, x_ds, y_ds = preprocess("rice_binned_kmeans.csv", 0.2, 7, True, [], [])

x_train, x_test, y_train, y_test, x_ds, y_ds = preprocess("wdbc_binned_kmeans.csv", 0.2, 1, True, ['ID'], [])

x_train, x_test, y_train, y_test, x_ds, y_ds = preprocess("wdbc_binned_kmeans.csv", 0.2, 1, True, ['ID'], [])

Run the implement function for diffrent models

In [97]:
#KNN
from sklearn.neighbors import KNeighborsClassifier
implement(KNeighborsClassifier())

Confusion matrix: 
[[74  1]
 [ 1 38]]
Classification report:               precision    recall  f1-score   support

           B       0.99      0.99      0.99        75
           M       0.97      0.97      0.97        39

    accuracy                           0.98       114
   macro avg       0.98      0.98      0.98       114
weighted avg       0.98      0.98      0.98       114

Accuracy score is: 0.9824561403508771
Precision score is: 0.9824561403508771
Recall score is: 0.9824561403508771
StratifiedKFold CV Accuracy: 0.9701 (+/- 0.0417)
StratifiedKFold CV Precision: 0.9707 (+/- 0.0413)
StratifiedKFold CV Recall: 0.9701 (+/- 0.0417)


In [98]:
#Ada Boost
from sklearn.ensemble import AdaBoostClassifier 
implement(AdaBoostClassifier(n_estimators=100, random_state = 10))

Confusion matrix: 
[[73  2]
 [ 0 39]]
Classification report:               precision    recall  f1-score   support

           B       1.00      0.97      0.99        75
           M       0.95      1.00      0.97        39

    accuracy                           0.98       114
   macro avg       0.98      0.99      0.98       114
weighted avg       0.98      0.98      0.98       114

Accuracy score is: 0.9824561403508771
Precision score is: 0.9833119383825417
Recall score is: 0.9824561403508771
StratifiedKFold CV Accuracy: 0.9737 (+/- 0.0423)
StratifiedKFold CV Precision: 0.9746 (+/- 0.0410)
StratifiedKFold CV Recall: 0.9737 (+/- 0.0423)


In [99]:
#SVM
from sklearn.svm import SVC 
implement(SVC(max_iter = -1, random_state=10))

Confusion matrix: 
[[74  1]
 [ 0 39]]
Classification report:               precision    recall  f1-score   support

           B       1.00      0.99      0.99        75
           M       0.97      1.00      0.99        39

    accuracy                           0.99       114
   macro avg       0.99      0.99      0.99       114
weighted avg       0.99      0.99      0.99       114

Accuracy score is: 0.9912280701754386
Precision score is: 0.9914473684210526
Recall score is: 0.9912280701754386
StratifiedKFold CV Accuracy: 0.9771 (+/- 0.0387)
StratifiedKFold CV Precision: 0.9779 (+/- 0.0373)
StratifiedKFold CV Recall: 0.9771 (+/- 0.0387)


In [100]:
#Gaussian Naive Bayes
from sklearn.naive_bayes import GaussianNB 
implement(GaussianNB())

Confusion matrix: 
[[71  4]
 [ 1 38]]
Classification report:               precision    recall  f1-score   support

           B       0.99      0.95      0.97        75
           M       0.90      0.97      0.94        39

    accuracy                           0.96       114
   macro avg       0.95      0.96      0.95       114
weighted avg       0.96      0.96      0.96       114

Accuracy score is: 0.956140350877193
Precision score is: 0.95828111946533
Recall score is: 0.956140350877193
StratifiedKFold CV Accuracy: 0.9385 (+/- 0.0705)
StratifiedKFold CV Precision: 0.9392 (+/- 0.0705)
StratifiedKFold CV Recall: 0.9385 (+/- 0.0705)


In [101]:
#Random Forests
from sklearn.ensemble import RandomForestClassifier
implement(RandomForestClassifier())


Confusion matrix: 
[[73  2]
 [ 1 38]]
Classification report:               precision    recall  f1-score   support

           B       0.99      0.97      0.98        75
           M       0.95      0.97      0.96        39

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114

Accuracy score is: 0.9736842105263158
Precision score is: 0.97400426742532
Recall score is: 0.9736842105263158
StratifiedKFold CV Accuracy: 0.9578 (+/- 0.0501)
StratifiedKFold CV Precision: 0.9588 (+/- 0.0490)
StratifiedKFold CV Recall: 0.9578 (+/- 0.0501)


In [102]:
#Decesion Trees
from sklearn.tree import DecisionTreeClassifier
implement(DecisionTreeClassifier())

Confusion matrix: 
[[72  3]
 [ 4 35]]
Classification report:               precision    recall  f1-score   support

           B       0.95      0.96      0.95        75
           M       0.92      0.90      0.91        39

    accuracy                           0.94       114
   macro avg       0.93      0.93      0.93       114
weighted avg       0.94      0.94      0.94       114

Accuracy score is: 0.9385964912280702
Precision score is: 0.9383656509695291
Recall score is: 0.9385964912280702
StratifiedKFold CV Accuracy: 0.9333 (+/- 0.0582)
StratifiedKFold CV Precision: 0.9346 (+/- 0.0596)
StratifiedKFold CV Recall: 0.9333 (+/- 0.0582)
